### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by LorenzoLuconi** [jwilder/docker-gen#105]
Docker v1.5 added IPv6 support, could you please add IPv6 addresses in the structure emitted by docker-gen?

**Comment by md5** [comment]
It doesn't look like the underlying library used by `docker-gen` supports IPv6: https://github.com/fsouza/go-dockerclient/search?utf8=%E2%9C%93&q=LinkLocalIPv6Address

Neither does samalba/dockerclient, the more popular Go library for the Docker API, though they at least have an open PR: https://github.com/samalba/dockerclient/pull/114

**Comment by jwilder** [comment]
Fixed via #122
