### ISSUE TITLE
Development: doc

### ISSUE THREAD

**Issue by Boran** [jwilder/docker-gen#109]
In the README to get going on development, it states 
```
$ git clone <your fork>
$ glock sync github.com/jwilder/docker-gen
$ make
```
For me (as a go newbie), the following worked better
```
$ git clone <your fork>
$ cd <your fork>
$ make get-deps
$ make
```
(Of course on ubuntu I also had to "sudo apt-get install golang" and add "export GOPATH=$HOME/src/go" to my bashrc.)
Then I experimented by making changes to docker-gen.go, making and testing as follows
```
sudo docker run -it -v $(pwd):/test -v /var/run/docker.sock:/var/run/docker.sock --rm debian  /test/docker-gen-sean -help
```

**Comment by jwilder** [comment]
Updated.  Thanks.
