### ISSUE TITLE
Volumes no longer working in docker 1.8.x

### ISSUE THREAD

**Issue by cybercode** [jwilder/docker-gen#111]
It seems that as of docker 1.8.1 (possibly 1.8.0?) the `Volumes` map returned by the api call no longer contain the actual host path, etc, but the data is in an array called `Mounts`. I have logged an issue ([15644](https://github.com/docker/docker/issues/15644)) against docker, but i don't know if this is a bug or expected change in behavior.

This of course makes the `$container.Volumes` useless in docker-gen templates.

**Comment by md5** [comment]
This was indeed a breaking change in Docker 1.8.x. There's already an open issue to fix this in `fsouza/go-dockerclient`, the underlying library used by `docker-gen`: https://github.com/fsouza/go-dockerclient/issues/350

**Comment by cybercode** [comment]
Should I close this issue or leave it as a reminder to review when the underlying library is fixed?

**Comment by jwilder** [comment]
Keep it open.

**Comment by md5** [comment]
Looks like `fsouza/go-dockerclient` has been updated in https://github.com/fsouza/go-dockerclient/commit/d22018657d6b35260cde9efef9ec18c061bfd86c

**Comment by itheiss** [comment]
Any news on this?

**Comment by md5** [comment]
Someone's going to need to update the `GLOCKFILE` with a newer ref. I took a quick pass at making the change and quickly ran into weird problems with the different Go dependency managers involved (`glock` for this projects and `party` for `fsouza/go-dockerclient`).

**Comment by cybercode** [comment]
fsouza/go-dockerclient has an incorrect fix (`Mounts` is specified in the config, not container). I have posted a fix in fsouza/go-dockerclient/issues/350 and tested it w/ a modified docker_client.go and it seems to work. Once docker-client is fixed i will submit my changes.

**Comment by cybercode** [comment]
the underlying library has been fixed. I have a question: should an update leave in the `Volumes` map for backwards compatibility, or should it be replaced entirely?

**Comment by md5** [comment]
It should leave it in place in case some is connecting to an older Docker
daemon.

**Comment by cybercode** [comment]
Note: New PR sent which simply add the `Mounts` as volumes to the existing `Volumes` map. This should make the underlying API changes transparent to docker-gen users.

**Comment by jwilder** [comment]
Fixed via #146
