### ISSUE TITLE
Trim host names of whitespace

### ISSUE THREAD

**Issue by mariusGundersen** [jwilder/docker-gen#121]
I've had an issue where I used comma and space to separate multiple `VIRTUAL_HOST`s, which caused the proxy to crash with the following error:

```
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /etc/nginx/conf.d/default.conf:118
```

This was caused by a space in the host value here: https://github.com/jwilder/docker-gen/blob/master/templates/nginx.tmpl#L52

This can be fixed if the value of `$host` is trimmed of whitespaces.

**Comment by jwilder** [comment]
Closing since issue is for `nginx-proxy`.
