### ISSUE TITLE
Separate Container Install: nginx.tmpl:52: function "trim" not defined

### ISSUE THREAD

**Issue by Boran** [jwilder/docker-gen#124]
Just tried the cut-and-paste example for 'Separate Container Install', nginx comes up fine, but nginx-gen gives
```
2015/10/09 06:40:41 unable to parse template: template: nginx.tmpl:52: function "trim" not defined
````
There is a trim() in https://github.com/jwilder/docker-gen/blob/master/template.go#L332, how come it does not find it?
Perhaps the image on dockerhub is behind this repo (and its readme)?
So I cloned this repo and build the image locally, but the same result.

Suggestions?

**Comment by md5** [comment]
The `trim` function is not in the 0.4.1 release of `docker-gen` that the image is using. The `Dockerfile` needs to be updated to pull in the latest 0.4.2 release that @jwilder pushed out this morning.

**Comment by Boran** [comment]
I updated Dockerfile and build locally and yes it built and runs fine.
Thanks.

**Comment by md5** [comment]
@Boran If you want to make a PR, I'm sure @jwilder would appreciate it.

**Comment by jwilder** [comment]
:+1:

**Comment by Boran** [comment]
Well there you go. Hopefully I got that complex patch right :-)
