### ISSUE TITLE
dockergen binary support for alpinelinux

### ISSUE THREAD

**Issue by hmalphettes** [jwilder/docker-gen#134]
Hi, I am curious if there is some interest in preparing a binary that works with Alpine Linux?

I built such binary following the same pattern than what @lorenz outlined for forego here:
https://github.com/ddollar/forego/issues/65#issuecomment-146521766

My Alpine based image of nginx-proxy weighs 23MB

Such a binary works also on glibc Linux distros; I have not tested that for a fact but if that helps here are my forego and dockergen binaries for x64: https://github.com/hmalphettes/nginx-proxy/releases/tag/0.0.0

Thanks for your attention.

**Comment by lorenz** [comment]
I have tested it, they work just fine as long as you don't use NSS (nobody uses that inside Docker).

**Comment by md5** [comment]
@lorenz What do you mean about NSS? `docker-gen` uses Go's `crypto/tls` library for TLS support.

**Comment by lorenz** [comment]
Sorry, meant nsswitch

**Comment by md5** [comment]
@lorenz Got it.

**Comment by md5** [comment]
That being said, the `docker-gen` binary is not only used inside Docker.
