### ISSUE TITLE
How do I trigger regeneration?

### ISSUE THREAD

**Issue by dmp1ce** [jwilder/docker-gen#135]
If I have a process running in the nginx-proxy container, how can I trigger docker-gen to regenerate the templates if it is using the `-watch` flag? Is there a command to touch the docker configuration that I'm not aware of?

The reason I want to do this is because I have updated the certificates in nginx-proxy and I want to regenerate the configuration with those files present.

**Comment by md5** [comment]
I don't think this is currently possible. I think it would be cool if this were possible by sending a `SIGHUP` to `docker-gen`.

**Comment by dmp1ce** [comment]
A workaround it to run docker-gen again with the same parameters minus the `-watch`.
