### ISSUE TITLE
[FEATURE REQUEST] label filtering

### ISSUE THREAD

**Issue by Ozzyboshi** [jwilder/docker-gen#141]
Right now docker-gen lets you filter containers by this switches :
- only-published
- only-exposed

I'd like ho have one more switch that cause docker-gen  to filter by label for example

docker-gen -only-labels REGEXP

In this case docker-gen should take into account only containers with at least one label matching REGEXP

With this new feature I will be sure not to write unwanted containers in my template file.
An alternative would be to manage the labels filter directly on my template file.

What do you think?
If you think this could be useful I am willing to write the implementation and make a pull request even if I am a Golang beginner.

**Comment by md5** [comment]
@Ozzyboshi How would you expect this to work? Would you expect your regular expression to match against both the label and its value? Or just the label itself?

**Comment by md5** [comment]
@Ozzyboshi This doesn't address your request directly, but I opened a PR for a set of `whereLabel*` functions that would allow you to do some of this work in the template itself: https://github.com/jwilder/docker-gen/pull/143

**Comment by Ozzyboshi** [comment]
@md5 My problem is that I have some containers running on my swarm cluster that I dont want to be published in my service discovery but they are considered by my docker-gen template.
At the end i solved in this way, take a look at 
https://github.com/Ozzyboshi/docker-consul-register/blob/master/consul.tmpl

This is my own custom template forked from jwilder/docker-register.
In this template, read from line 30: if the env variable CONTAINER_LABELNAME is set then publish containers only with a certain label equals to a certain value.
I thought it was better to move this part from the template to docker-gen itself adding a new feature like docker ps --filter does.
In my mind docker-gen could act like this (like docker does) :
docker-gen -f (or --filter) key=value pair
for example

 docker-gen --filter "foo=bar" --filter "bif=baz" ...

However i think your PL would solve the problem anyway, so for now I am going to close this issue.Feel free to reopen it if you think changing docker-gen itself should have some benefits.
