### ISSUE TITLE
Make exists reactive

### ISSUE THREAD

**Issue by mitar** [jwilder/docker-gen#150]
It would be great if `exists` command would start watching the path, so that if file appears or disappears, template would be recreated. Currently it seems it checks the path only at the template generation time. So even if the file is later on created or removed, template is not recreated.

Probably the same for `dir`. Are there any other non-pure functions?

**Comment by jwilder** [comment]
`exists` just checks if a file exists at the time the template is executed.  It's not possible for it to watch a file or dir.  If you are changing files or dirs used by templates, you can manually re-trigger `docker-gen` to regenerate templates after you modify those files by sending the process a `SIGHUP` signal now.  You could send that signal after you change the files or you might be able to use something like `inotify-utils` to monitor those files/dirs and then send the signal when an event is received.

**Comment by mitar** [comment]
> t's not possible for it to watch a file or dir.

What do you mean it is not possible? You can use [fsnotify](https://github.com/go-fsnotify/fsnotify) for this? This could really be done automatically so that one does not have to manually recreate checks and send signals?

**Comment by jwilder** [comment]
I meant it's not possible to use file/dir watching from the `exists` template function.  When `docker-gen` generates a template, it doesn't know what that template does.  It simply renders the template with some variables and hooks for functions to be used in the template and that's it.  Once the template is rendered, `docker-gen` doesn't have any state to get notified that a directory or file used by the template has changed.

It would be possible to have a command-line option such as `-watch-dir` that `docker-gen` could then setup notification hooks and re-generate the template if something changed in that dir.
