### ISSUE TITLE
Compose env bugs

### ISSUE THREAD

**Issue by Nox-404** [jwilder/docker-gen#157]
Hi, i noticed that in docker-compose file it doesn't work
if env vars are set in this format :

```
environment:
  - VIRTUAL_PORT 8080
  - VIRTUAL_HOST plop.com
```

But it works with :

```
environment:
  - VIRTUAL_PORT=8080
  - VIRTUAL_HOST=plop.com
```

> Notice the ```=```

Not sure that it's your concern or docker-compose one...

**Comment by jwilder** [comment]
I don't know if your first example is valid for docker-compose.  If it is, I'd say it's bug there.
