### ISSUE TITLE
docker-gen command doesn't exit

### ISSUE THREAD

**Issue by falcon15500** [jwilder/docker-gen#159]
Hi there,

When I run the docker-gen command from within the container, it performs as expected however it never seems to exit (back to the command line)?

I would expect this behaviour with -interval or -watch, but I am not using either of these.  At present it sits there (after completing it's activity) until I hit CTRL-C.

Mike

**Comment by jwilder** [comment]
Can you provide some steps to reproduce this issue?

**Comment by falcon15500** [comment]
Sure, I have just 'exec'ed into my docker-gen container and run the following:

root@3d80941b0a7d:/# /usr/local/bin/docker-gen -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

Which just resulted in (as expected):

2016/02/05 22:34:57 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification ''

But after that it doesn't exit.  It just sits there doing nothing and I have to CTRL-C to get back to the command line.

M.

**Comment by falcon15500** [comment]
I would expect execution to continue in the cases of -watch and -interval however without either of those options, I would expect execution to be a 1 shot deal and to exit cleanly?

Is this not expected behaviour?

**Comment by nilroy** [comment]
@jwilder I am also facing the same issue as @falcon15500
