### ISSUE TITLE
Blank Lines In Generated Configuration

### ISSUE THREAD

**Issue by maxexcloo** [jwilder/docker-gen#16]
While this issue is cosmetic in nature I was wondering if there's any way it can be fixed/prevented as readability is severely impaired with many hosts.

An example template I use is here: https://github.com/maxexcloo/Docker/blob/master/apps/haproxy-config/haproxy.tmpl

**Comment by shabble** [comment]
It seems to be a failing^Wfeature of golang templates. You can work around it (somewhat horribly) by writing templates like:

    {{ with $foo := something }}{/*
        /*}{{ do stuff $foo }}{/*
    */}}
    {{ end }}

(That is, using a newline spanning comment tag to eat the newline while still being able to indent for style)

**Comment by thaJeztah** [comment]
Aw, that's ugly. That being said, yes, the current output is ugly too :smile:

**Comment by md5** [comment]
I don't know that fixing this at the level of template processing is going to be maintainable, but it seems like having a `docker-gen -skip-blank-lines` flag would let the user skip blank lines in the cases that they know it's safe to do so (e.g. most config files).
