### ISSUE TITLE
#159 changed exit code

### ISSUE THREAD

**Issue by spali** [jwilder/docker-gen#163]
probably by mistake, the fix of #159 did break exit code.
currently the exit code is always 0 even the file did change or not.
I would suppose to exit with != 0 when nothing changed and 0 when the file has changed.

**Comment by jwilder** [comment]
The only time `docker-gen` exited w/ a non-zero exit code is when the flags were not all set.  It has always exited w/ 0.

**Comment by spali** [comment]
Ok thanks, then you can see this as an optional feature request or just close it.

Am 17. Februar 2016 23:45:05 MEZ, schrieb Jason Wilder <notifications@github.com>:
