### ISSUE TITLE
Generate something for container by name

### ISSUE THREAD

**Issue by gobwas** [jwilder/docker-gen#170]
Hello!
Thanks for the great tool! 

Is it possible to generate some thing (nginx config for my case) only for one container?
Something like this:
```
docker-gen -include=my_container_name vhost.tmpl
```

Thanks!

**Comment by jwilder** [comment]
You could do that by adding a check in your templates using a local env variable.

```
CONTAINER=my_container_name docker-gen vhost.tmpl
```

In your template:
```
{{range $key, $value := .}}
{{ if eq $value.Name $.ENV.CONTAINER_NAME }}
 # template goes here for your container
{{ end}
{{ end }}

{{end}}

**Comment by gobwas** [comment]
@jwilder Yeah, realized the same opportunity right now =)
Thank you very much, and sorry for disturbing )
