### ISSUE TITLE
Add option for delaying notify-signal

### ISSUE THREAD

**Issue by JonasT** [jwilder/docker-gen#176]
Right now dockergen works very badly for me, and I'm somewhat certain it is because the container getting notify-signal reloads the config too quickly after a new service was created, immediately tries to contact it and decides it is dead because the new service hasn't actually finished starting the program and opening the port yet.

Therefore, it appears an option to delay the notify-signal would possibly really help me a lot. I tried something like `-notify 'bash -c "sleep 10; docker kill -s HUP proxy_proxy_1"'` as a workaround but that doesn't work either because inside the dockergen container there is no actual docker binary present...

**Comment by jwilder** [comment]
Did you try `-wait`?

**Comment by JonasT** [comment]
I use `jwilder/docker-gen` from the docker registry as a container, and I checked `docker-gen --help` for options where this one isn't listed. It sounds exactly like what I need, but maybe you'd want to add it to the `--help` options page so people can find it :-)

**Comment by jwilder** [comment]
@JonasT Are you sure you have the latest image pulled down?  It's available in `0.7.0` and also the `latest` tag and is reported via `-h` flag.

**Comment by JonasT** [comment]
WHoops, it was actually outdated. Sorry, my fault :-) also thanks for pointing me in the right direction!

**Comment by JonasT** [comment]
Hm one question though, is the minimum duration measured from the last event? Or from the last generation?

Because the latter seems like it would only randomly solve the issue, and not in all cases...
