### ISSUE TITLE
/opt/go/src/github.com/jwilder/docker-gen/generator.go:349: cannot use apiInfo (type *docker.DockerInfo) as type *docker.Env in argument to SetServerInfo

### ISSUE THREAD

**Issue by lroguet** [jwilder/docker-gen#183]
Hi,

I'm trying to build a version of your nginx-proxy for the ARM architecture but building my Docker image (from that [Dockerfile](https://github.com/lroguet/rpi-nginx-proxy/blob/master/Dockerfile)) fails at the following line
`RUN go get -u github.com/jwilder/docker-gen`
with
`/opt/go/src/github.com/jwilder/docker-gen/generator.go:349: cannot use apiInfo (type *docker.DockerInfo) as type *docker.Env in argument to SetServerInfo`

```
$ docker version
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.4.3
 Git commit:   c3959b1
 Built:        Wed Feb 24 09:51:38 2016
 OS/Arch:      linux/arm
```

Not sure how to proceed from there.

**Comment by jwilder** [comment]
You need to use glock to setup dependencies. Instructions are at the bottom of the README. Also, there are ARM builds under [releases](https://github.com/jwilder/docker-gen/releases/tag/0.7.0).
