### ISSUE TITLE
Conditional notify-sighup ?

### ISSUE THREAD

**Issue by 00angus** [jwilder/docker-gen#184]
@jwilder that's a really cool project and really useful :)

I'd like to ask if it's possible to implement the following:

- docker-gen will restart or not the service (`notify-sighup`) based on decisions taken inside the template

It would be useful to not restart the DNS service if the templates do not produce an output (based on internal logic of the template).
Currently I'm using `docker-gen` to produce part of my DNS zone files (_bind dns_ - forward and reverse), and It's working perfectly. My templates generates zone entries from the container name and for every container that start/stop `docker-gen` reload named. 
But for a certain kind of names I don't generate a dns entry, so in that case `docker-gen` should _not_ signal HUP to the dns container.

Is it possible to obtain such a behaviour?

**Comment by 00angus** [comment]
Just to better explain: if the template doesn't output things, of course, docker-gen will not restart/notify.

What I'd like is the ability to generate an output from the template, leaving to the template itself to choose IF the notify should take place.

Do you think it may be useful/interesting ?

**Comment by jwilder** [comment]
That would be pretty complicated to support because the templates are opaque to `docker-gen`.  It just generates and compares the new output w/ the existing.
