### ISSUE TITLE
Cannot seem to run on host.

### ISSUE THREAD

**Issue by derek-adair** [jwilder/docker-gen#191]
➜  _utilities ./docker-gen
zsh: exec format error: ./docker-gen

I'm runnin on `osx 10.10.1`.  I've tried it with;

server api: 1.10.1 and 1.8.3
client api: 1.21, 1.20, 1.19, 1.18

Running on virtualbox as well if thats relevant.

**Comment by jwilder** [comment]
Did you download the correct binary?  You may be running the osx binary under linux or vice versa.

https://github.com/jwilder/docker-gen/releases/tag/0.7.1

**Comment by derek-adair** [comment]
![its true, i am dumb](https://media.makeameme.org/created/BREAKING-NEWS-I-0nt0kr.jpg)

**Comment by derek-adair** [comment]
![i feel like an idiot](http://i.imgur.com/kSnmG8Q.gif)
