### ISSUE TITLE
Routing requests

### ISSUE THREAD

**Issue by ghost** [jwilder/docker-gen#194]
I have a container running nginx server ( listening on port 80 ) and i have installed docker-gen in it. I have used the template from [nginx-proxy](https://github.com/jwilder/nginx-proxy). There are two other containers in the same host which are started as follows : 
docker run -e VIRTUAL_HOST=django.localhost.com -e VIRTUAL_PORT=8000 -d -p 8000:8000 --expose=8000  test/django-docker

docker run -e VIRTUAL_HOST=flask.localhost.com -e VIRTUAL_PORT=4100 -d -p 4100:4100 --expose=4100 --entrypoint=/opt/webapp/flask.sh test/flask bash

The relevant part of the conf generated by docker gen is :
upstream django.localhost.com {
                                ## Can be connect with "bridge" network
                        # romantic_jennings
                        server 172.17.0.2:8000;
}
server {
        server_name django.localhost.com;
        listen 80 ;
        location / {
                proxy_pass http://django.localhost.com;
        }
}
upstream flask.localhost.com {
                                ## Can be connect with "bridge" network
                        # goofy_mclean
                        server 172.17.0.3:4100;
}
server {
        server_name flask.localhost.com;
        listen 80 ;
        location / {
                proxy_pass http://flask.localhost.com;
        }
}

When I do curl 127.0.0.1, i get only django page, being the first server entry may be. So, I have added the entries flask.localhost.com & django.localhost.com in /etc/hosts and directed them to 127.0.0.1. Then, I can access django && flask using curl django.localhost.com &&  curl flask.localhost.com through nginx respectively. Is there any other method to do this, can docker-gen automatically do this rather than adding entries to /etc/hosts file? 
And if I wanted to design a template such that nginx listens on multiple ports for each service behind it, how can I go about it? Listen port inside server block has to be changed dynamically. Can this be done?

**Comment by ovidiub13** [comment]
First, what you're doing with the `/etc/hosts` file is simulating a DNS entry in a DNS server on your host machine. Nginx receives the requested domain when you access it, with curl in this case. `docker-gen` has nothing to do with allocating DNS entries or changing your `/etc/hosts` file. That's not it's purpose.

As a workaround, you can write your own script and put it in a cron (or make it trigger when the nginx config has changed) and update your `/etc/hosts` with the relevant virtual hosts domains.

----

For the making your own template, all the information you need is in the [Readme](https://github.com/jwilder/docker-gen/blob/master/README.md)

**Comment by jwilder** [comment]
Another thing you can do is setup `dnsmasq` and configure it as your DSN resolver for your `localhost.com` domain or some other local domain.  There are lots of [tutorials](http://harold.internal.org/using-dnsmasq-on-osx-sierra-for-local-dev-domain-wildcards/) out there that can help you get it setup.

The the way it works is that you have `dnsmasq` handling wildcard domains for something like `.dev`.  Then you start you containers w/ `flask.dev` and `django.dev` domains.  `nginx-proxy` will proxy those domains to the appropriate containers.  When you `curl django.dev`, `dnsmasq` will resolve `django.dev` to whatever you have configured (usually `127.0.0.1`) and you'll be able to access your containers the way you were expecting.
