### ISSUE TITLE
DEFAULT_HOST as in nginx-proxy

### ISSUE THREAD

**Issue by kachkaev** [jwilder/docker-gen#206]
​I'm using `nginx` + `docker-gen` instead of jst [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) as this is recommended in [`docker-letsencrypt-nginx-proxy-companion`'s README](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion). This method is considered safer because a publicly-facing nginx container does not have access to the docker's socket.

I am setting up a server with a few projects hosted at sub-domains, something like `a.example.com`, `b.example.com`, `a.b.c.d.e.example.com`, etc. DNS is set up so that all subdomains of all levels point to the front-end nginx. When using `nginx-proxy`, it is possible to handle all hosts for which there is no corresponding container with `VIRTUAL_HOST` by a container with `VIRTUAL_HOST`=`DEFAULT_HOST`. This can be useful, e.g. to redirect from mistyped subdomains to the main domain or to show some nice error message.

How could `DEFAULT_HOST` fit into `docker-gen` image?

**Comment by gravufo** [comment]
I have the same setup and it would be nice to see this feature integrated.

**Comment by jwilder** [comment]
Just use the template from nginx-proxy. The templates in this repo are just samples to help people get started creating their own templates.
