### ISSUE TITLE
Can't use docker-gen notify-sighup with Docker Cloud, container names are dynamic

### ISSUE THREAD

**Issue by lizter** [jwilder/docker-gen#209]
I am trying to use docker-gen together with an nginx container on Docker Cloud. I am having trouble with the sighup sent by docker-gen when e.g. my application containers changes config. Docker Cloud generates random names for my containers, e.g. `nginx-test-1.test.7321ba3a`. I can't specify `container_name` in the [Docker Cloud Stack YAML file](https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/) as you can with docker-compose.

The error I get is:
```
Sending container 'nginx-test' signal '1'
Error sending signal to container: No such container: nginx-test
```
Is there any way to utilize e.g. `links: nginx-test` or something to work around this? Alternatives? I don't know Go, so I am having trouble looking over the code.

**Comment by jwilder** [comment]
Not currently.  #77 sounds similar.  I think `docker-gen` would need to be able to signal a container using something other than names.  Possibly labels, images, etc..  That is not possible right now.

**Comment by Theaxiom** [comment]
This guy did it, could you please duplicate his changes?
- https://hub.docker.com/r/donovanmuller/docker-gen-docker-cloud/

**Comment by Theaxiom** [comment]
It really sucks that I am not able to use this on Docker Cloud

**Comment by A34** [comment]
this guy too: https://hub.docker.com/r/helder/docker-gen/

**Comment by Theaxiom** [comment]
Thanks @A34 I will definitely be using that image. 👍
