### ISSUE TITLE
Watch dir

### ISSUE THREAD

**Issue by bnason** [jwilder/docker-gen#220]
Can docker-gen watch a folder for changes? For instance, I'd like to watch /etc/nginx/vhosts.d/ so that a change to any file in that dir will trigger a reload of nginx.

**Comment by jwilder** [comment]
No.  It can't currently do that right now, but that functionality could be added.  You might be able to use `inotify-tools` as a workaround and send a `SIGHUP` to `docker-gen` to trigger a reload.

Something like:

```
while inotifywait /etc/nginx/vhost.d -r -e modify,create,delete -qq; do kill -hup $(pgrep docker-gen); done;
```
