### ISSUE TITLE
Send other signals than SIGHUP

### ISSUE THREAD

**Issue by ptxmac** [jwilder/docker-gen#242]
I'm working on a caddy based alternative to nginx-proxy, but caddy is listening for `USR1` to reload the config instead of `HUP`. It would be useful if docker-gen could send other signals.

**Comment by SerialVelocity** [comment]
Afaik I know this is supported if using a configuration file since you write `[container name|container id] = [signal]`

**Comment by ptxmac** [comment]
Yeah, not sure what I was thinking when I created this task. It works fine :)
