### ISSUE TITLE
Add a way to filter out containers in templates

### ISSUE THREAD

**Issue by vlcinsky** [jwilder/docker-gen#26]
Just following the last sentence from README (TODO).

Current set of functions allowed in templates is very limited and does not allow much filtering.

Even subset from following functions would help:

- equality of strings
- test, if a string is present in an array of string (for this we need also a function to define in template the array of string)
- wildcard matching
- startsWith

**Comment by dataferret** [comment]
I'd be interested in something like where too. Although intersect would be nice too for those moments where we have a comma list of filter tags and a comma list of env tags.  Any work so far on bringing some of the Hugo stuff over?

**Comment by jwilder** [comment]
Closing this w/ since #54 has landed.  Equality/prefix/suffix and a few where functions should provide better ability to filter containers in templates.  We can open new issues/PR for other template functions that would be useful.
