### ISSUE TITLE
please include docker-gen-alpine-linux-armhf-$(TAG).tar.gz in releases

### ISSUE THREAD

**Issue by morriswinkler** [jwilder/docker-gen#260]
Hello Mister Wilder,

is it possible to add the statically linked alpine bin to the release tab?
Or are there any issues that prevent that?

Sincerely,

Morris

**Comment by jwilder** [comment]
It's already there: https://github.com/jwilder/docker-gen/releases/tag/0.7.3.  Named `docker-gen-alpine-linux-amd64-0.7.3.tar.gz`

**Comment by morriswinkler** [comment]
I was referring to the armhf version, not amd64, it exists within the Makefile but not the release tab.

Makefile
```
        mkdir -p dist/alpine-linux/armhf && GOOS=linux GOARCH=arm GOARM=6 go build -ldflags "$(LDFLAGS)" -a -tags netgo -installsuffix netgo -o dist/alpine-linux/armhf/docker-gen ./cmd/docker-gen
```
So to speak docker-gen-alpine-linux-armhf-0.7.3.tar.gz is missing.

BTW:
Have you seen https://github.com/docker-library/official-images#multiple-architectures, I don't know if this will be available to all images hosted on docker hub, but the convention is definitely arm32v6. Which makes much more sense then armhf, which is used to imply that an EABI with VFP2/3  is used which is available from ARM v6 upwards, also ARM v5 support VFP1 but that is not supported in go and anyway only implemented by a few vendors. You see how confusing this term is. arm32v6 tells you that it is 32 bit ARM v6,  armhf could be anything from ARM v6 to v8, adding the variation 32 / 64 bit in v8, even if v8 is always  v8 in go this is not obvious to a user of your docker image. 

For all those reasons I would advise you to call the port arm32v6.

Sincerely,

Morris Winkler

**Comment by jwilder** [comment]
Ah, sorry.  Misread the issue.  The `armhf` target was added after `0.7.3` release.  It will be part of the next version though.

I don't actually use the arm targets personally.  I don't have any issue changing them if something else is more standard though.

**Comment by morriswinkler-simplesurance** [comment]
Should I make a PR for the makefile changes, because as it is the docker-gen inside alpine will not work since it is still linked to stdc lib.

**Comment by morriswinkler-simplesurance** [comment]
By the way the amd64 file is also not working within the alpine cotainer, same problem 
if you run file on dist/alpine-linux/amd64/dist-gen you get:
```
dist/alpine-linux/amd64/docker-gen: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cb2f6a8c98ed8d44d3eb5e0fe048f5feee45556a, not stripped
```
/lib64/ld-linux-x86-64.so.2 is not part of alpine.

**Comment by morriswinkler-simplesurance** [comment]
I advise you to read https://medium.com/@diogok/on-golang-static-binaries-cross-compiling-and-plugins-1aed33499671 is a very good blogpost regarding go in docker containers.

**Comment by dealancer** [comment]
Any updates on this? I am not seeing any ARM releases on this page https://hub.docker.com/r/jwilder/docker-gen/tags.

**Comment by dealancer** [comment]
@jwilder I realized that there is an ARM release on the releases tab of the GitHub, but is there any plans to automatically upload such releases to DockerHub or is there a way around I can use releases directly from GitHub in my compose file without need to rebuild them?

**Comment by jimaldon** [comment]
Piggybacking on this: is there support planned for `arm64/aarch64`?
