### ISSUE TITLE
docker-gen not working with env variable `NETWORK_ACCESS=internal` 

### ISSUE THREAD

**Issue by returntrip** [jwilder/docker-gen#278]
This line `COPY network_internal.conf /etc/nginx/` is missing from the `docker-gen` `Dockerfile`

All works fine when I manually mount  [network_internal.conf](https://github.com/jwilder/nginx-proxy/blob/3ef600a3b56105fa4ac343ef6d10b2c52818fec0/network_internal.conf) and use the [nginx-proxy](https://github.com/jwilder/nginx-proxy/blob/226bfe158fc90b057cec727a7dd36b7a078cbe49/nginx.tmpl) from https://github.com/jwilder/nginx-proxy

I thought `nginx-proxy` and `docker-gen` were kept in sync but I guess that is not the case. I am wondering if other changes from `nginx-proxy` have not been merged into `docker-gen` and viceversa.

**Comment by jwilder** [comment]
`nginx-proxy` and `docker-gen` are separate projects.  `nginx-proxy` has it's own template and uses `docker-gen`.  `docker-gen` doesn't have any templates other than example ones to help people get started.

**Comment by returntrip** [comment]
@jwilder thanks for the clarification. If that is the case tho (that `docker-gen` does not share the `nginx.tmpl` template with `nginx-proxy`) the `nginx-proxy` [README.md](https://github.com/jwilder/nginx-proxy/blob/master/README.md) should be corrected on the section "Separate Containers" as it statues this:

"To run nginx proxy as a separate container you'll need to have [nginx.tmpl](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl) on your host system."

The template linked there is the `nginx-proxy` template one. Hope I was clear.
