### ISSUE TITLE
Using cfg files with Docker Compose

### ISSUE THREAD

**Issue by cutterbl** [jwilder/docker-gen#285]
Is there a way to use .cfg files with Docker Compose? I have not been able to find an example of this anywhere, and all of my attempts have hit walls.

I would like to define a directory of .cfg files, for different templating for different environments, and have it automatically run each [[config]], but I just haven't figured out how to accomplish this.

**Comment by jwilder** [comment]
You should be able to pass a config file as an arg in docker-compose.  You wouldn't be able pass a dir and have it read all the config though.
