### ISSUE TITLE
Manually run docker-gen to create vhosts of running containers.

### ISSUE THREAD

**Issue by arisxama** [jwilder/docker-gen#286]
Is there any way to recreate current containers default.conf file manually? Ofcourse running containers are being created with required env vars. Seems that docker-gen is buggy and sometimes it misses some of the apps that are being created.

**Comment by jwilder** [comment]
You can run docker-gen manually or send it a sighup signal to regenerate the template.

**Comment by arisxama** [comment]
thanks for your answer @jwilder and thanks for this aweome project.

Creating containers with proper env vars stopped working with no obvious reason. Had this set up working for a month then it just stopped. 

However, trying to manually run docker-gen /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf (both folders and files exist with write access) result in uncompleted process. Is there any way to debug?
