### ISSUE TITLE
Compatibility with future Go versions

### ISSUE THREAD

**Issue by Bo98** [jwilder/docker-gen#338]
Just a heads up that Go 1.17 (and the just-released 1.16 without first changing `GO111MODULE`) won't support builds that aren't in module-aware mode.

I'm not sure what the status of this project is. Is there any plans to migrate to Go modules?

https://blog.golang.org/go116-module-changes

**Comment by tkw1536** [comment]
I've made a PR to address this https://github.com/jwilder/docker-gen/pull/341.
