### ISSUE TITLE
Make a new tagged release.

### ISSUE THREAD

**Issue by buchdag** [jwilder/docker-gen#342]
@jwilder, could you make a new tagged release with the important fixes made in #327, #336 and #341 ?

**Comment by jwilder** [comment]
Sure

**Comment by jwilder** [comment]
https://github.com/jwilder/docker-gen/releases/tag/0.7.5

**Comment by buchdag** [comment]
@jwilder if you have time, having another tagged release now that #345, #346 and #347 are merged would be very helpful.
