### ISSUE TITLE
Support generating content for stopped containers

### ISSUE THREAD

**Issue by azilbersteinSFDC** [jwilder/docker-gen#51]
Please enable a possibility to generate template instances for stopped containers, not just running ones.
This could come in a form of a flag for docker-gen, -also-stopped-containers, for example. This is equivalent to the -a flag of docker ps.

The main use-case is when generating a fluentd configuration file. The best practice is to regenerate the configuration file and restart fluentd. However consider what happens to a short-lived container, one that crashes seconds after it starts. On receiving the stop event, the fluentd configuration file will no longer refer to that container, and logs from this container will probably be lost.

**Comment by jwilder** [comment]
See #130

**Comment by jwilder** [comment]
Fixed via #130
