### ISSUE TITLE
docker-gen on Cluster

### ISSUE THREAD

**Issue by apexskier** [jwilder/docker-gen#68]
Does anyone have any knowledge of if it's possible to run docker-gem monitoring a cluster, possibly using [Swarm](https://github.com/docker/swarm/)?

**Comment by md5** [comment]
@apexskier it should be possible by setting the Swarm master as your `-endpoint` and setting the TLS-related flags. You'll have to make sure you have a key and certificate (possibly borrowed from boot2docker or Docker Machine) and the CA certificate.

**Comment by apexskier** [comment]
Great, thanks for the info. I'll update once I've worked on this.

**Comment by jwilder** [comment]
#71 adds some swarm Node info that can be used within templates now.

**Comment by JustAdam** [comment]
I wrote a post [here](http://www.before.no/2015/04/using-docker-gen-with-a-swarm-cluster/) with some details, and which hopefully makes some sense.

**Comment by md5** [comment]
> You can probably use the official nginx image; but here is another one just in case. The difference here is it writes the logs to stdout/stderr.

The default `nginx` also writes its logs to stdout/stderr, it just does so via a pair of symlinks under `/var/log`. cf. https://github.com/nginxinc/docker-nginx/blob/e9202a4795d84a85499fcd6cda58ddde4cf4079d/Dockerfile#L15-L16

**Comment by JustAdam** [comment]
thank you
