### ISSUE TITLE
Please include example for NotifyContainers in example.cfg

### ISSUE THREAD

**Issue by ypid** [jwilder/docker-gen#70]
In the source code, it is defined as:

    NotifyContainers: make(map[string]docker.Signal)

But as I do not (yet) know Go. I am not able write a valid configuration with this option. Can someone please add an example for this?

**Comment by jwilder** [comment]
I don't think that is configurable via the config file at the moment.  Likely a bug.  An example for specifying a notify command can be found here: https://github.com/jwilder/docker-gen/blob/master/examples/docker-gen.cfg#L5

**Comment by ypid** [comment]
Thanks for the hint. I already tried to use "notifycmd" but it did not reload the nginx configuration. I wanted to use "-notify-sighup" in the configuration file which worked nicely as command line parameter while moving to multiple configuration files generated by docker-gen.

In which context is "notifycmd" executed? I run docker-gen itself in an docker container.
Is it true that generating multiple configuration files with one docker-gen instance requires the use of a configuration file?

**Comment by jwilder** [comment]
Oh.  If you're running docker-gen in a container, then `notify-sighup` is what you would need.  It should be configurable via the config file but looks like there is a bug so it's only able to be used via the command line at the moment.

I added #73 to track that bug.

**Comment by ypid** [comment]
Thanks

**Comment by emsi** [comment]
@ypid: Please take a look at:
https://github.com/emsi/docker-gen/blob/6f32cc3f4c6c398028a6214abf4baf26a8a2aa52/examples/docker-gen.cfg
I think it's the syntax you are looking for.

**Comment by jwilder** [comment]
README and examples were updated previously.
