### ISSUE TITLE
Notify HUP not working from config file

### ISSUE THREAD

**Issue by jwilder** [jwilder/docker-gen#73]
There appears to be no way to configure a `-notify-sighup` option via a config file.  This should be possible.

**Comment by emsi** [comment]
+1 on this :)

**Comment by alefi87** [comment]
+1

**Comment by emsi** [comment]
Actually it even works without the patch. :)
All you need to do is use proper syntax in template file as shown in the 6f32cc3f4c6c398028a6214abf4baf26a8a2aa52

Or check:
https://raw.githubusercontent.com/emsi/Docker/master/docker-gen/docker-gen.cfg
and 
https://github.com/emsi/Docker/tree/master/docker-gen

**Comment by jwilder** [comment]
Thanks @emsi!
