### ISSUE TITLE
Expose container hostname in the RuntimeContainer struct

### ISSUE THREAD

**Issue by deviantony** [jwilder/docker-gen#74]
Is it possible to expose the container name in the RuntimeContainer structure? I'd like to use it in a DNS solution to provide container inter-communication based on their hostnames.

**Comment by md5** [comment]
It already is: https://github.com/jwilder/docker-gen/blob/582ce75d888fbd4a8407c7c1ec859de58cf53a39/docker-gen.go#L60

**Comment by deviantony** [comment]
Oh my bad then ;)

Thanks for the quick response.

**Comment by md5** [comment]
No worries.

BTW, you might want to have a look at https://github.com/tianon/rawdns

**Comment by deviantony** [comment]
I will, thanks for the suggestion !
