### ISSUE TITLE
Generate multiple files at once

### ISSUE THREAD

**Issue by nunofgs** [jwilder/docker-gen#78]
Hi @jwilder,

I was toying around with the idea of a Docker container that starts an *avahi* daemon with configuration generated from other containers (much like [nginx-proxy](https://github.com/jwilder/nginx-proxy))

So for example, to announce *samba* through *avahi* we could simply:

`$ docker run -e SERVICE_NAME=MySambaServer nunofgs/samba`

The problem is that *avahi* requires that services be added individually to the `/etc/avahi/services/` folder but *docker-gen* only outputs one file.

Is there any way to use *docker-gen* to generate multiple files at once?

**Comment by md5** [comment]
I know this isn't what you're asking for, but how about having `docker-gen -notify` to run a command that can break the single file output into multiple files. That should at least get you a working setup.

**Comment by nunofgs** [comment]
That's the only solution I see so far as well and it's what I'll end up doing. Thanks for the suggestion.

I almost didn't create this issue since it seems out of scope for *docker-gen* but I thought I'd ask anyway and get the discussion started.

Maybe this could be explained with an example?

**Comment by jwilder** [comment]
I think @md5 suggestion is the best way to do this currently.
