### ISSUE TITLE
Question: How to catch the IP of the container that has no exposed ports?

### ISSUE THREAD

**Issue by njuaplusplus** [jwilder/docker-gen#79]
The Address struct in the [Docker Gen Emit Structure](https://github.com/jwilder/docker-gen/wiki/Docker-Gen-Emit-Structure)
shows that only when there has exposed port, the ip address can be stored in the Address structure.
However,  it's not necessary that expose the port of the container.
So how can I get the ip address of such kind of container?

Thank you so much!

**Comment by jwilder** [comment]
Doesn't appear to be a way to do that right now but should be an easy fix.  The code that sets the IP is here: https://github.com/jwilder/docker-gen/blob/master/docker_client.go#L132.  Probably just need to add a top-level `IP` field.

**Comment by njuaplusplus** [comment]
@jwilder Thank you. Though I don't know golang, I will try it.

**Comment by mjaverto** [comment]
@njuaplusplus did you successfully get that working?
