### ISSUE TITLE
Separate config per container 

### ISSUE THREAD

**Issue by andrexus** [jwilder/docker-gen#80]
Is there any possibility to define a separate template for each container separately?
For example I have one host with many containers and some containers need different templates (some, with SSL, some without, some with extra options defined)

**Comment by thaJeztah** [comment]
Have a look at https://github.com/jwilder/nginx-proxy#custom-nginx-configuration, which supports separate configuration files per virtual host.

**Comment by andrexus** [comment]
It looks like there is no easy way to define separate template. The solution doesn't look nice, but thank you for your help

**Comment by jwilder** [comment]
I'm not exactly sure how you are using `docker-gen` but you can generate multiple templates using a config file.  See https://github.com/jwilder/docker-gen/blob/master/examples/docker-gen.cfg
