### ISSUE TITLE
Use labels instead of environment variables 

### ISSUE THREAD

**Issue by mariusGundersen** [jwilder/docker-gen#81]
The latest version of docker let's you label a container with metadata, associating a string value to a string key. This seems like a better fit for VIRTUAL_HOST than using environment variables

**Comment by thaJeztah** [comment]
I think both can make sense. One advantage of env is that they are accessible inside the container, which can be handy.

Nonetheless, adding support for labels could be nice :)

**Comment by md5** [comment]
I believe this can be closed now.

**Comment by jwilder** [comment]
Fixed by #82
