### ISSUE TITLE
Must pass an array or slice to 'whereExist'

### ISSUE THREAD

**Issue by ybogdanov** [jwilder/docker-gen#99]
Hi,

What am I doing wrong?

```bash
$ docker run --rm -ti jwilder/docker-gen -version
0.4.0
```

logstash-forwarder.json.tmpl:
```
{{whereExist . "Labels.logs" | len}}
```

```bash
$ docker run --rm -ti -v `pwd`/templates:/templates -v /var/run/docker.sock:/tmp/docker.sock jwilder/docker-gen -watch /templates/logstash-forwarder.json.tmpl /etc/logstash-forwarder.json
2015/07/16 07:13:41 template error: template: logstash-forwarder.json.tmpl:1:2: executing "logstash-forwarder.json.tmpl" at <whereExist . "Labels...>: error calling whereExist: Must pass an array or slice to 'whereExist'; received &[0xc208000d80 0xc208001560 0xc2080017a0 0xc208001c20 0xc2080a2120 0xc2080a2360 0xc2080a26c0 0xc2080a2b40 0xc2080a2fc0]
```

**Comment by md5** [comment]
What does `.` refer to at that point in your template? The error message doesn't make it very clear what was received if it isn't an array or slice. That error message could probably be improved to say something more useful...

Also, what is it you're trying to do?

**Comment by ybogdanov** [comment]
I'm trying to filter out the list of containers and keep only those which have label "logs" present. `.` is a root object, which is `[]*RuntimeContainer`.

**Comment by md5** [comment]
If that were the case, then you wouldn't be getting that error.

`$` is *the* root object. `.` is only set to the root object initially. If you use `template`, `with`, or `range`, then `.` will get a new value inside that context.

**Comment by ybogdanov** [comment]
```
{{whereExist . "Labels.logs" | len}}
```
Is the actual full content of the template.

This doesn't work either:
```
{{whereExist $ "Labels.logs" | len}}
```

**Comment by ybogdanov** [comment]
```bash
$ echo '{{whereExist $ "Labels.logs" | len}}' > template.tmpl && docker run --rm -ti -v `pwd`/template.tmpl:/template.tmpl -v /var/run/docker.sock:/tmp/docker.sock jwilder/docker-gen -watch /template.tmpl /template.out
2015/07/17 05:56:28 template error: template: template.tmpl:1:2: executing "template.tmpl" at <whereExist $ "Labels...>: error calling whereExist: Must pass an array or slice to 'whereExist'; received &[0xc208000c60 0xc208001320 0xc208000900 0xc2080017a0 0xc208001b00 0xc20809e120 0xc20809e5a0 0xc20809e000 0xc20809e7e0 0xc20809eb40]
```

**Comment by ybogdanov** [comment]
@md5 please run this command yourself and see what happens:

```bash
echo '{{whereExist $ "Labels.logs" | len}}' > template.tmpl && docker run --rm -ti -v `pwd`/template.tmpl:/template.tmpl -v /var/run/docker.sock:/tmp/docker.sock jwilder/docker-gen -watch /template.tmpl /template.out
```

**Comment by ybogdanov** [comment]
It doesn't work from the latest master either:
```bash
docker-gen [master] $ echo '{{whereExist . "Labels.logs" | len}}' > template.tmpl && ./docker-gen template.tmpl template.out
2015/07/17 09:13:43 template error: template: template.tmpl:1:2: executing "template.tmpl" at <whereExist . "Labels...>: error calling whereExist: Must pass an array or slice to 'whereExist'; received &[0xc2080a6240 0xc2080a6000 0xc2080a6a20 0xc2080a6d80 0xc2080a7320 0xc2080a77a0 0xc2080a7c20 0xc208000fc0 0xc208001b00]
```

**Comment by ybogdanov** [comment]
I wanted to clarify, why there is a pointer here? https://github.com/jwilder/docker-gen/blob/master/template.go#L370
Tests run without it and I don't see and sense of making it a pointer. And the bug is actually because of it.

**Comment by md5** [comment]
That appears to have changed in this commit: https://github.com/jwilder/docker-gen/commit/2fe6ff54f222b06079fd446a84f9976e28b303f1

You're right that there's not strictly any reason for that to be a pointer. Still, it might be better to make it so that `generalizedWhere` can accept a pointer to an array or slice. I think that wrapping a call to `reflect.Indirect` around this line could help: https://github.com/jwilder/docker-gen/blob/master/template.go#L71

**Comment by md5** [comment]
Oops, just looked at your fix! I think both of our fixes would do the same thing, but calling `reflect.Indirect` would avoid the recursive call to `generalizedWhere`.

**Comment by webner** [comment]
@ybogdanov: The current master should already work with your example. Are you sure you actually used the latest binary?

```
docker-gen :: (master) » git rev-parse HEAD
f622fc71c231cd94207a8dfcd65c99d122dbacf0
docker-gen :: (master) » go build
docker-gen :: (master) » echo '{{whereExist . "Labels.logs" | len}}' > template.tmpl && ./docker-gen template.tmpl
0
```

**Comment by ybogdanov** [comment]
Yes, it works now. I used compiled binary from the latest master at the time I was testing. Sha was 08d45c8

Looks like the issue can be closed now.
